### ISSUE TITLE
Raw `Result` in redaction macro

### ISSUE THREAD

**Issue by tjkirch** [google/argh#97]
https://github.com/google/argh/blob/329890897aac903864c6b3e1672d8ce32a3ef5c3/argh_derive/src/lib.rs#L437-L438

(Introduced in https://github.com/google/argh/pull/91)

This raw `Result` can cause type confusion where the user's `type Result` alias is used instead of `std::result::Result`, causing compilation failure.

```
error[E0107]: this type alias takes 1 type argument but 2 type arguments were supplied
   --> main.rs:205:10
    |
205 | #[derive(FromArgs, PartialEq, Debug)]
    |          ^^^^^^^^- help: remove this type argument
    |          |
    |          expected 1 type argument
    |
note: type alias defined here, with 1 type parameter: `T`
   --> main.rs:23:6
    |
23  | type Result<T> = std::result::Result<T, error::Error>;
    |      ^^^^^^ -
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Other places in argh use `std::result::Result`, and if I change that one spot to `std::result::Result` as well, argh and my application once again test fine.

**Comment by djc** [comment]
I'm seeing similar issues with `String`; we have some places where we shadow `String` with `smartstring::alias::String` and this makes argh fail. Note that as a regression from 0.1.4 to 0.1.5, this violates semver, so I'd recommend yanking 0.1.5 unless this can be resolved quickly.

**Comment by otavio** [comment]
This is indeed a very inconvenient issue. Could this be fixed soon?

**Comment by yjh0502** [comment]
Is it possible to publish fixed version to crates.io ?
